[package]
name = "counter"
version = "0.1.0"
authors = ["Baojun Wang <wangbj@fb.com>"]
edition = "2018"

[lib]
name = "counter"
crate-type = ["cdylib"]
path = "src/lib.rs"

[dependencies]
reverie-helper = { path = "../../reverie-helper" }
log = { version = "0.4", default-features = false }
